@baseUrl = http://localhost:8082

### Create job
POST {{baseUrl}}/jobs
Content-Type: application/json

{
  "command": "echo hello"
}

### List jobs
GET {{baseUrl}}/jobs
Content-Type: application/json



### Worker debug
GET http://localhost:8090