FROM golang:1.25.5-alpine AS builder

WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/worker ./cmd/worker

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /out/worker ./worker

CMD ["./worker"]
